#!/bin/bash

[ "${PREFIX}" == "" ] && PREFIX=/afs/cern.ch/work/y/ylevinse/public/venv_py27_slc6


[ "${GCC_SETUP}" == "" ] && GCC_SETUP=gcc47-slc5-setup.sh

# install python
PYVER_MAJOR=2.7
PYVER_MINOR=4

. build_inits

. build_functions

# set afs access rights etc..
setup_prefix $PREFIX

download_files || exit 1

install_python || exit 1

cd $BUILD_DIR
. ${PREFIX}/bin/activate


python ez_setup.py || exit 1
python ez_setup.py -U setuptools || exit 1

#checking:
echo "Using python binary: `which python`"
echo "Using easy_install: `which easy_install`"

# We need some additional libraries in a more
# modern version.. Not for SLC6?
# install_tcltk || exit 1

# installing other modules..
cd $BUILD_DIR
install_numpy || exit 1

cd $BUILD_DIR
easy_installs || exit 1

cd $BUILD_DIR
install_h5py || exit 1

# Install PLACET/HTGEN
install_placet_htgen || exit 1

# Finally, we install pymad.. because I want to ;)
cd $BUILD_DIR
install_pymad || exit 1

