#!/bin/bash

#[ "${PREFIX}" == "" ] && PREFIX=/afs/cern.ch/work/y/ylevinse/public/venv_py27_slc6
[ "${PREFIX}" == "" ] && PREFIX=/afs/cern.ch/work/y/ylevinse/public/venv_py27_slc6_gcc


#[ "${SETUP_COMPILER}" == "" ] && SETUP_COMPILER=IntelCompilers.sh && SETUP_ARGS=intel64
[ "${SETUP_COMPILER}" == "" ] && SETUP_COMPILER=gcc48-slc6-setup.sh

# install python
PYVER_MAJOR=2.7
PYVER_MINOR=5

. build_inits

. build_functions

# set afs access rights etc..
setup_prefix $PREFIX

download_files || exit $?
install_python || exit $?



cd $BUILD_DIR
. ${PREFIX}/bin/activate

python get-pip.py || exit $?
pip install setuptools || exit $?

#checking:
echo "Using python binary: `which python`"
echo "Using pip: `which pip`"

# installing other modules..
cd $BUILD_DIR
pip_installs || exit $?

# Install PLACET/HTGEN
install_placet_htgen || exit 1

# Install GUINEA-PIG
install_guineapig || exit 1

# Install pyevolve
cd $BUILD_DIR
install_pyevolve || exit 1

# Finally, we install pymad.. because I want to ;)
cd $BUILD_DIR
install_pymad || exit 1

