#!/bin/env bash

download_files() {
    if [ ! -f $PYTHON_VERSION.tar.bz2 ] 
    then
        wget http://www.python.org/ftp/python/${PYVER}/$PYTHON_VERSION.tar.bz2
    fi
    
    if [ ! -f ez_setup.py ] 
    then
        wget http://peak.telecommunity.com/dist/ez_setup.py
    fi
    
    if [ ! -f setuptools-0.6c11-py${PYVER_MAJOR}.egg ]
    then
        wget http://pypi.python.org/packages/${PYVER_MAJOR}/s/setuptools/setuptools-0.6c11-py${PYVER_MAJOR}.egg#md5=fe1f997bc722265116870bc7919059ea
    fi
    if [ ! -e matplotlib-${MPL_VER}.tar.gz ]
    then 
        wget http://sourceforge.net/projects/matplotlib/files/matplotlib/matplotlib-${MPL_VER}/matplotlib-${MPL_VER}.tar.gz/download?_test=goal
    fi
}


install_python() {
    if [ ! -d $PYTHON_VERSION ]
    then
        echo "Extracting tarball..."
        tar xvfj $PYTHON_VERSION.tar.bz2 > /dev/null
        echo "Done"
    fi

    # building python itself..
    cd $PYTHON_VERSION
    ./configure --prefix=$PREFIX
    make
    make install
    
    cd ..
    
    # setting environment...
    cp -f activate_base activate
    echo -e "export PATH=$PREFIX/bin/:\$PATH\n" >> activate
    echo -e "export LD_LIBRARY_PATH=$PREFIX/lib/:\$LD_LIBRARY_PATH\n" >> activate
    mv activate ${PREFIX}/bin/
}

install_tcltk() {
    for f in "tcl${TCLTK_VER} tk${TCLTK_VER}"
    do
        if [ ! -e "${f}-src.tar.gz" ]
        then
            wget http://prdownloads.sourceforge.net/tcl/${f}-src.tar.gz
        fi
        [ -d "${f}" ] && rm -rf $f
        tar xvfz ${f}-src.tar.gz
        
        cd ${f}/unix
        ./configure --prefix=${PREFIX}
        make install
        cd ../../
    done
}

install_matplotlib() {
    if [ -d matplotlib-${MPL_VER} ]
    then
        rm -rf matplotlib-${MPL_VER}
    fi
    tar xvfz matplotlib-${MPL_VER}.tar.gz
    cd matplotlib-${MPL_VER}
    python setup.py install

}
install_numpy() {
    echo "Downloading numpy.."
    if [ -d numpy ]
    then
        cd numpy; git pull
    else
        git clone git://github.com/numpy/numpy.git > /dev/null
        cd numpy
    fi
    echo "Done"
    python setup.py build --fcompiler=gnu95
    python setup.py install
    cd ..
    echo "numpy installed"
}

easy_installs() {
#    easy_install matplotlib
    easy_install scipy
    easy_install ipython
    easy_install cython
    easy_install sympy
    easy_install pyyaml
    easy_install pexpect
}

install_h5py() {
    easy_install h5py
    if (( $? != 0 ))
    then
        if [ ! -d hdf5-1.8.7-linux-static.tar.gz ]
        then
            wget http://www.hdfgroup.org/ftp/HDF5/current/bin/linux/hdf5-1.8.7-linux-static.tar.gz
        fi
        echo "Extracting hdf5..."
        tar xvfz hdf5-1.8.7-linux-static.tar.gz > /dev/null
        echo "Done"
        
        HDF5_DIR=$PREFIX/ easy_install h5py
    fi
}

install_madx() {
    [ ! -d "madX" ] && svn checkout http://svnweb.cern.ch/guest/madx/trunk/madX/
    cd madX
    svn update
    [ -d "build" ] && rm -rf build
    mkdir build;cd build
    cmake \
        -DMADX_STATIC=OFF
        -DBUILD_SHARED_LIBS=ON \
        -DCMAKE_INSTALL_PREFIX=${PREFIX} \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        ../
    make install
    cd ../
}

install_pymad() {
    install_madx
    [ ! -d "pymad" ] && git clone git@github.com:pymad/pymad.git
    cd pymad
    git pull
    cd src
    python setup.py install
    cd ../../
}

