#!/bin/bash

PREFIX=/afs/cern.ch/user/y/ylevinse/scratch1/python27

# install python
PYVER_MAJOR=2.7
PYVER_MINOR=2
PYVER=${PYVER_MAJOR}.${PYVER_MINOR}

PYTHON_VERSION=Python-${PYVER}

mkdir -p $PREFIX
download_files() {
    if [ ! -f $PYTHON_VERSION.tar.bz2 ] 
    then
        wget http://www.python.org/ftp/python/${PYVER}/$PYTHON_VERSION.tar.bz2
    fi
    
    if [ ! -f ez_setup.py ] 
    then
        wget http://peak.telecommunity.com/dist/ez_setup.py
    fi
    
    if [ ! -f setuptools-0.6c11-py${PYVER_MAJOR}.egg ]
    then
        wget http://pypi.python.org/packages/${PYVER_MAJOR}/s/setuptools/setuptools-0.6c11-py${PYVER_MAJOR}.egg#md5=fe1f997bc722265116870bc7919059ea
    fi
}
download_files

install_python() {
    if [ ! -d $PYTHON_VERSION ]
    then
        echo "Extracting tarball..."
        tar xvfj $PYTHON_VERSION.tar.bz2 > /dev/null
        echo "Done"
    fi

    # building python itself..
    cd $PYTHON_VERSION
    ./configure --prefix=$PREFIX
    make
    make install
    
    cd ..
    
    # setting environment...
    cp -f activate_base activate
    echo -e "export PATH=$PREFIX/bin/:\$PATH\n" >> activate
    echo -e "export LD_LIBRARY_PATH=$PREFIX/lib/:\$LD_LIBRARY_PATH\n" >> activate
}
install_python
. activate

#checking:
echo "Using python binary: `which python`"
echo "Using easy_install: `which easy_install`"


python ez_setup.py
python ez_setup.py -U setuptools


# installing other modules..
install_numpy() {
    echo "Downloading numpy.."
    if [ -d numpy ]
    then
        cd numpy; git pull
    else
        git clone git://github.com/numpy/numpy.git > /dev/null
        cd numpy
    fi
    echo "Done"
    python setup.py build --fcompiler=gnu95
    python setup.py install
    cd ..
    echo "numpy installed"
}
install_numpy

easy_installs() {
    easy_install matplotlib
    easy_install ipython
    easy_install scipy
    easy_install cython
    easy_install sympy
    easy_install pyyaml
    easy_install pexpect
}
easy_installs

install_h5py() {
    if [ ! -d hdf5-1.8.7-linux-static.tar.gz ]
    then
        wget http://www.hdfgroup.org/ftp/HDF5/current/bin/linux/hdf5-1.8.7-linux-static.tar.gz
    fi
    echo "Extracting hdf5..."
    tar xvfz hdf5-1.8.7-linux-static.tar.gz > /dev/null
    echo "Done"
    
    HDF5_DIR=$PREFIX/ easy_install h5py
}
install_h5py


