#!/bin/bash

# install python

PYTHON_VERSION=Python-2.7.2
PREFIX=/afs/cern.ch/user/y/ylevinse/scratch1/python27

mkdir -p $PREFIX

if [ ! -f $PYTHON_VERSION.tar.bz2 ] 
then
    wget http://www.python.org/ftp/python/2.7.2/$PYTHON_VERSION.tar.bz2
fi

if [ ! -f ez_setup.py ] 
then
    wget http://peak.telecommunity.com/dist/ez_setup.py
fi

if [ ! -f setuptools-0.6c11-py2.7.egg ]
then
    wget http://pypi.python.org/packages/2.7/s/setuptools/setuptools-0.6c11-py2.7.egg#md5=fe1f997bc722265116870bc7919059ea
fi

if [ ! -d $PYTHON_VERSION ]
then
    tar xvfj $PYTHON_VERSION.tar.bz2
fi
cd $PYTHON_VERSION
./configure --prefix=$PREFIX
make
make install

cd ..
rm -r $PYTHON_VERSION.tar.bz2
rm -r $PYTHON_VERSION

PATH=$PREFIX/$PYTHON_VERSION/bin/:$PATH
which python
exit 1
$PREFIX/$PYTHON_VERSION/bin/python ez_setup.py
$PREFIX/$PYTHON_VERSION/bin/python ez_setup.py -U setuptools

# cd $PREFIX/$PYTHON_VERSION/bin

which easy_install # checking..

easy_install numpy
easy_install matplotlib
easy_install ipython
easy_install scipy
easy_install cython
easy_install sympy
easy_install pyyaml
easy_install pexpect

cd $PREFIX
wget http://www.hdfgroup.org/ftp/HDF5/current/bin/linux/hdf5-1.8.7-linux-static.tar.gz
tar xvfz hdf5-1.8.7-linux-static.tar.gz
cd $PREFIX/$PYTHON_VERSION/bin
HDF5_DIR=$PREFIX/hdf5-1.8.7-linux-static easy_install h5py

